### ISSUE TITLE
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47

### ISSUE THREAD

**Issue by Username13211** [AliaksandrSiarohin/first-order-model#285]
How to fix this error?

**Comment by AliaksandrSiarohin** [comment]
In colab?

**Comment by ghost** [comment]
Yes in colab, can it run without gpu?

**Comment by AliaksandrSiarohin** [comment]
You should change device to gpu in settings.

**Comment by ghost** [comment]
> You should change device to gpu in settings.

I tried changing to GPU but it says it's not available and it always is not available for me atleast. Please tell me how to run it with cpu? You mentioned use --cpu but I don't know where to put it. Also I am new to colab so please help me.

**Comment by tombets2424** [comment]
Yes I have the same error. Google limits how often you can use colab (well limits you if you don't pay $10 per month) so if you use the bot often you get a temporary block. I believe the GPU provided by google is needed to execute the code. Otherwise it gets stopped at code block 5. I am trying to use jupyter locally to see if I can bypass this and use the bot as much as I like. I don't really know what I am doing but if it works, I will let you know.

**Comment by ghost** [comment]
> Yes I have the same error. Google limits how often you can use colab (well limits you if you don't pay $10 per month) so if you use the bot often you get a temporary block. I believe the GPU provided by google is needed to execute the code. Otherwise it gets stopped at code block 5. I am trying to use jupyter locally to see if I can bypass this and use the bot as much as I like. I don't really know what I am doing but if it works, I will let you know.

I installed jupyter, run it from cmd, copy and pasted the link of jupyter notebook to colab but it says can't connect even though that server was online.

**Comment by tombets2424** [comment]
Follow this exact tutorial and it will work. Luckily I managed to find this to install it locally and it works great. https://youtu.be/ICvNnrWKHmc
