### ISSUE TITLE
GPU RTX 3090 - RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by r06521601** [AliaksandrSiarohin/first-order-model#302]
My environment is:

GPU :  RTX 3090
cudatoolkit :  11.0.221
pytorch :  1.8.0.dev20201005
torchvision :  0.8.0.dev20201007

any one has solution? 

`
C:\Users\pc006\.conda\envs\face2\lib\site-packages\torch\nn\functional.py:3105: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
  0%|                                                                                                                       | 0/4 [00:00<?, ?it/s]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\pc006\.conda\envs\face2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\pc006\.conda\envs\face2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "webcam.py", line 100, in make_animation
    use_relative_jacobian=relative, adapt_movement_scale=adapt_movement_scale)
  File "C:\Users\pc006\Desktop\faceswap\animate.py", line 33, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: no kernel image is available for execution on the device
`

**Comment by r06521601** [comment]
finally It work!

I comment all about jacobian part

I don't know why lol?

**Comment by Prosspik** [comment]
yo how did you fix it im on a 3080

**Comment by r06521601** [comment]
> yo how did you fix it im on a 3080

hi, I founded that the pytorch inverse function is weird with 3090, so I translated the matrix to cpu mode before inverse the matrix.

ref:
`
torch.inverse(matrix.cpu()).cuda()
`

**Comment by Prosspik** [comment]
Could you go into more detail on

> > yo how did you fix it im on a 3080
> 
> hi, I founded that the pytorch inverse function is weird with 3090, so I translated the matrix to cpu mode before inverse the matrix.
> 
> ref:
> `torch.inverse(matrix.cpu()).cuda()`

Could you go into more detail on how you went about translating the matrix to cpu mode before inversing the matrix?
Thanks in advance

**Comment by Travsh** [comment]
> Could you go into more detail on
> 
> > > yo how did you fix it im on a 3080
> > 
> > 
> > hi, I founded that the pytorch inverse function is weird with 3090, so I translated the matrix to cpu mode before inverse the matrix.
> > ref:
> > `torch.inverse(matrix.cpu()).cuda()`
> 
> Could you go into more detail on how you went about translating the matrix to cpu mode before inversing the matrix?
> Thanks in advance

There are two .py with torch.inverse()

dense_motion.py
            #jacobian = torch.matmul(kp_source['jacobian'], torch.inverse(kp_driving['jacobian']))
            test_inverse = torch.inverse(kp_driving['jacobian'].cpu())
            jacobian = torch.matmul(kp_source['jacobian'], test_inverse.cuda())

animate.py
            #jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
            test_inverse = torch.inverse(kp_driving_initial['jacobian'].cpu())
            jacobian_diff = torch.matmul(kp_driving['jacobian'], test_inverse.cuda())

@r06521601 Thank you for saving my day!

**Comment by Prosspik** [comment]
> > Could you go into more detail on
> > > > yo how did you fix it im on a 3080
> > > 
> > > 
> > > hi, I founded that the pytorch inverse function is weird with 3090, so I translated the matrix to cpu mode before inverse the matrix.
> > > ref:
> > > `torch.inverse(matrix.cpu()).cuda()`
> > 
> > 
> > Could you go into more detail on how you went about translating the matrix to cpu mode before inversing the matrix?
> > Thanks in advance
> 
> There are two .py with torch.inverse()
> 
> dense_motion.py
> #jacobian = torch.matmul(kp_source['jacobian'], torch.inverse(kp_driving['jacobian']))
> test_inverse = torch.inverse(kp_driving['jacobian'].cpu())
> jacobian = torch.matmul(kp_source['jacobian'], test_inverse.cuda())
> 
> animate.py
> #jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
> test_inverse = torch.inverse(kp_driving_initial['jacobian'].cpu())
> jacobian_diff = torch.matmul(kp_driving['jacobian'], test_inverse.cuda())
> 
> @r06521601 Thank you for saving my day!

OH MY GOD THANK YOU SO MUCH MAN YOU AND @r06521601 JUST SAVED ME!

**Comment by Travsh** [comment]
> > > Could you go into more detail on
> > > > > yo how did you fix it im on a 3080
> > > > 
> > > > 
> > > > hi, I founded that the pytorch inverse function is weird with 3090, so I translated the matrix to cpu mode before inverse the matrix.
> > > > ref:
> > > > `torch.inverse(matrix.cpu()).cuda()`
> > > 
> > > 
> > > Could you go into more detail on how you went about translating the matrix to cpu mode before inversing the matrix?
> > > Thanks in advance
> > 
> > 
> > There are two .py with torch.inverse()
> > dense_motion.py
> > #jacobian = torch.matmul(kp_source['jacobian'], torch.inverse(kp_driving['jacobian']))
> > test_inverse = torch.inverse(kp_driving['jacobian'].cpu())
> > jacobian = torch.matmul(kp_source['jacobian'], test_inverse.cuda())
> > animate.py
> > #jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
> > test_inverse = torch.inverse(kp_driving_initial['jacobian'].cpu())
> > jacobian_diff = torch.matmul(kp_driving['jacobian'], test_inverse.cuda())
> > @r06521601 Thank you for saving my day!
> 
> OH MY GOD THANK YOU SO MUCH MAN YOU AND @r06521601 JUST SAVED ME!

I just find that model.py also have torch.inverse() . 

model.py
                #normed_driving = torch.inverse(kp_driving['jacobian'])
                normed_driving = torch.inverse(kp_driving['jacobian'].cpu()).cuda()


Edit: My CPU workload is running up to 80% while training. It's feel like CPU is slowing down the training.
As the GPU seems to wait CPU

**Comment by superwhyun** [comment]
That exactly happens to me, and I fixed the problem by updating python 3.8.13 from 3.7.x, and installed latest PyTorch 1.12.1. 
It was not needed to comment out any code.

**Comment by yangqing-yq** [comment]
> 

@superwhyun unbelievable. the required torch version is 1.0.0, while you use the latest one. there should be huge gap in the apis.

**Comment by yangqing-yq** [comment]
> That exactly happens to me, and I fixed the problem by updating python 3.8.13 from 3.7.x, and installed latest PyTorch 1.12.1. It was not needed to comment out any code.

cool!

**Comment by invisiblewealth** [comment]
I got it to work using:

Python 3.10.14, pip install torch==2.0.1+cu118 torchvision==0.15.2--index-url https://download.pytorch.org/whl/cu118

Just make sure you use a torch, torchvision that is compatible with your Cuda version
