### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by khalestorm** [AliaksandrSiarohin/first-order-model#384]
A few errors:
1. demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. 
2.  "AssertionError: Torch not compiled with CUDA enabled"

My source video is an mp4 off youtube that's been processed by face-alignment and converted with ffmpeg. Using a 256x256 px source image.

I have a Radeon and not Nvidia GPU, so I want to run this without CUDA

(base) kyle@MacBook-Pro first-order-model % python demo.py  --config config/vox-256.yaml --driving_video crop.mp4 --source_image Noe_crop.jpg --checkpoint vox-cpk.pth.tar --relative --adapt_scale
demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 144, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 32, in load_checkpoints
    generator.cuda()
  File "/Users/kyle/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/Users/kyle/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/Users/kyle/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/Users/kyle/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/Users/kyle/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/Users/kyle/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/Users/kyle/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
(base) kyle@MacBook-Pro first-order-model %

**Comment by AliaksandrSiarohin** [comment]
Try to add ```--cpu``` flag.

**Comment by wurst-case** [comment]
@AliaksandrSiarohin doesn't this run it on the cpu which is slower? I am getting the same error but I do have gpus with cuda.

**Comment by dylan-cm** [comment]
For non NVIDIA users: --cpu flag will fix this.

If you get this error with an NVIDIA gpu, you will need to install PyTorch with cuda enabled. You can do that by following the PyTorch install instructions on their [GitHub found here.](https://github.com/pytorch/pytorch#installation)

**Comment by srajalcodes** [comment]
> For non NVIDIA users: --cpu flag will fix this.
> 
> If you get this error with an NVIDIA gpu, you will need to install PyTorch with cuda enabled. You can do that by following the PyTorch install instructions on their [GitHub found here.](https://github.com/pytorch/pytorch#installation)

How to add --cpu flag?

**Comment by poinwater** [comment]
> > For non NVIDIA users: --cpu flag will fix this.
> > If you get this error with an NVIDIA gpu, you will need to install PyTorch with cuda enabled. You can do that by following the PyTorch install instructions on their [GitHub found here.](https://github.com/pytorch/pytorch#installation)
> 
> How to add --cpu flag?

If you are using function such as 
```
from demo import load_checkpoints
generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
                            checkpoint_path='../resources/model/vox-cpk.pth.tar')
```
Just pass a parameter cpu = True
```
from demo import load_checkpoints
generator, kp_detector = load_checkpoints(cpu=True, config_path='config/vox-256.yaml', 
                            checkpoint_path='../resources/model/vox-cpk.pth.tar')
```
If you are using command line
```
python demo.py --config config/vox-256.yaml --driving_video crop.mp4 --source_image Noe_crop.jpg --checkpoint vox-cpk.pth.tar --relative --adapt_scale
```
Add --cpu like
```
python demo.py --config config/vox-256.yaml --cpu --driving_video crop.mp4 --source_image Noe_crop.jpg --checkpoint vox-cpk.pth.tar --relative --adapt_scale
```
It works for me.
